<%@ Page Title="Batching" Language="C#" MasterPageFile="~/ATCP.Master"
    CodeBehind="ATCPFacultyHome.aspx.cs" Inherits="ATCPClient.ATCPFacultyHome" MaintainScrollPositionOnPostback = "true" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
     <style>
            .gridview-header
            {
                font-weight: bold;
                font-size: 10px;
                padding-bottom: 3px;
                color:  #666666;
                padding-top: 3px;
                font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;
                background-color: #EEEEEE;
                width:auto;
            }
     </style>
    <script>
    </script>
</asp:Content>

    <asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server" EnableViewState="true">
        <div class="container">
<%--            <div class="row">
                <div class="col-3">
                    <label class="font-weight-bold" for="searchName" style="font-size: 13px;">Search By NetID:</label>
                    <asp:TextBox ID="searchTextBox" runat="server" style="font-size: small" class="form-control form-control-sm" aria-describedby="firstname"></asp:TextBox>
                </div>
                <div class="col-2">
                    <label class="font-weight-bold" for="searchName" style="font-size: 13px;"></label> 
                    <asp:Button style="font-family:Calibri" class="btn btn-dark form-control my-2 btn-sm" Text="Search" runat="server" OnClick="Unnamed_Click" Height="30px" />
                </div>
                <div class="col-5"></div>
            </div>--%>
            <div class="row my-4">
                <div class="d-flex col justify-content-start">
                    <div class="card" style="width: 70rem;">
                        <div class="card-header font-weight-bold">
                            <asp:Label Id="LblStudentName" style="font-family:Calibri" runat="server" />
                        </div>
                        <div class="card-body" id="cardBodyData">
                        
                    <asp:GridView ID="GridView1" runat="server" AutoGeneratedColumns="false" ShowFooter="true" DataKeyNames="FacultyID"

                        Width="100%"
                        CssClass="gridview"
                        ShowHeaderWhenEmpty="true"
                        OnRowEditing="GridView1_RowEditing"
                        OnRowCancelingEdit="GridView1_CancellingEdit"
                        OnRowUpdating="GridView1_RowUpdating"
                        OnRowDeleting="GridView1_RowDeleting"
                        OnRowCommand="GridView1_RowCommand"
                        BackColor="White" BorderColor="#CCCCCC" BorderStyle="None" BorderWidth="1px" CellPadding="3" EnableModelValidation="True" AutoGenerateColumns="False">

                        <FooterStyle BackColor="White" ForeColor="#000066" />
                        <HeaderStyle Font-names="Calibri" BackColor="#006699" Font-Bold="True" ForeColor="White"/>
                        <PagerStyle BackColor="White" ForeColor="#000066" HorizontalAlign="Left" />
                        <RowStyle ForeColor="#000066" />
                        <SelectedRowStyle BackColor="#669999" Font-Bold="True" ForeColor="White" />
                <%--<SortedAscendingCellStyle BackColor="#F1F1F1">--%>

                        <Columns>
                            <asp:TemplateField HeaderText="NetID">
                                <ItemTemplate>
                                    <div style="width: 80px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="font-family:Calibri; width:10px" ID="txtNetID" Text='<%# Eval("NetID") %>' runat="server" />
                                    </div>
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 80px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="width: 80px;font-family:Calibri" ID="txtNetID" Text='<%# Eval("NetID") %>' runat="server" /><%-- to make this editable just change Lable to textboxs--%>
                                    </div>                                    
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 80px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 80px;font-family:Calibri" ID="txtNetIDFooter" runat="server" />
                                    </div>                           
                                </FooterTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="First Name">
                                <ItemTemplate>
                                    <div style="width: 120px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="font-family:Calibri" Text='<%# Eval("Fname") %>' runat="server" />
                                    </div>                                   
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 120px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 120px;font-family:Calibri" ID="txtFname" Text='<%# Eval("Fname") %>' runat="server" />
                                    </div>                                 
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 120px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 120px;font-family:Calibri" ID="txtFnameFooter" runat="server" />
                                    </div>                                    
                                </FooterTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="Last Name">
                                <ItemTemplate>
                                    <div style="width: 120px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="font-family:Calibri" Text='<%# Eval("Lname") %>' runat="server" />
                                    </div>                                  
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 120px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 120px;font-family:Calibri" ID="txtLname" Text='<%# Eval("Lname") %>' runat="server" />
                                    </div>                                   
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 120px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 120px;font-family:Calibri" ID="txtLnameFooter" runat="server" />
                                    </div>                                   
                                </FooterTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="Adjunct">
                                <ItemTemplate>
                                    <div style="width: 60px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <%--<asp:Label style="font-family:Calibri" Text='<%# Eval("isAdjunct") %>' runat="server" />--%> 
                                        <asp:CheckBox style="width: 60px;font-family:Calibri;padding-left:25px" onclick="return false;" Checked='<%# Eval("isAdjunct") %>' ID="txtAdjunct" runat="server" />
                                    </div>                                  <%-- Checked='<%# Bind("isAdjunct") %>'--%>
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 60px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:CheckBox style="width: 60px;font-family:Calibri;padding-left:25px" Checked='<%# Eval("isAdjunct") %>' ID="txtAdjunct" runat="server" />  <%--Text='<%# Eval("isAdjunct") %>'--%>
                                    </div>                                  
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 60px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:CheckBox style="width: 60px;font-family:Calibri;padding-left:25px" ID="txtAdjunctFooter" runat="server" /> 
                                    </div>                                  
                                </FooterTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="UIC Email">
                                <ItemTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="font-family:Calibri" Text='<%# Eval("UICEmail") %>' runat="server" />
                                    </div>                                    
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 150px;font-family:Calibri" ID="txtUICEmail" Text='<%# Eval("UICEmail") %>' runat="server" />
                                    </div>                                   
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 150px;font-family:Calibri" ID="txtUICEmailFooter" runat="server" />
                                    </div>                                  
                                </FooterTemplate>
                            </asp:TemplateField>

                            <asp:TemplateField HeaderText="Office Phone">
                                <ItemTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="font-family:Calibri" Text='<%# Eval("OfficePhone") %>' runat="server" />
                                    </div>                                    
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 150px;font-family:Calibri" ID="txtOfficePhone" Text='<%# Eval("OfficePhone") %>' runat="server" />
                                    </div>
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 150px;font-family:Calibri" ID="txtOfficePhoneFooter" runat="server" />
                                    </div>                                  
                                </FooterTemplate>
                            </asp:TemplateField>

                           <asp:TemplateField HeaderText="Work Cell Phone">
                                <ItemTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:Label style="font-family:Calibri" Text='<%# Eval("WorkCellPhone") %>' runat="server" />
                                    </div>                                   
                                </ItemTemplate>
                                <EditItemTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 150px;font-family:Calibri" ID="txtWorkCellPhone" Text='<%# Eval("WorkCellPhone") %>' runat="server" />
                                    </div>                                   
                                </EditItemTemplate>
                                <FooterTemplate>
                                    <div style="width: 150px; overflow: hidden; white-space: nowrap; text-overflow: ellipsis">
                                        <asp:TextBox style="width: 150px;font-family:Calibri" ID="txtWorkCellPhoneFooter" runat="server" />
                                    </div>                                  
                                </FooterTemplate>
                            </asp:TemplateField>

                    <asp:TemplateField>
                        <ItemTemplate>
                            <div class="row">
                            <div class="col-6">
                                 <asp:Button style="font-family:Calibri" class="btn btn-dark form-control my-2 btn-sm" Text="Edit" runat="server" CommandName="Edit" ToolTip="Edit" Height="30px" />
                            </div>
                            <div class="col-6">
                                 <asp:Button style="font-family:Calibri" class="btn btn-dark form-control my-2 btn-sm" Text="Delete" runat="server" CommandName="Delete" ToolTip="Delete" Height="30px" />
                             </div>   
                                </div>                        
                        </ItemTemplate>
                        <EditItemTemplate>
                            <div class="row">
                                <div class="col-6">
                                     <asp:Button style="font-family:Calibri" class="btn btn-dark form-control my-2 btn-sm" Text="Update" runat="server" CommandName="Update" ToolTip="Edit" Height="30px" />
                                </div>
                                <div class="col-6">
                                    <asp:Button style="font-family:Calibri" class="btn btn-dark form-control my-2 btn-sm" Text="Cancel" runat="server" CommandName="Cancel" ToolTip="Cancel" Height="30px" />
                                </div>
                            </div>
                        </EditItemTemplate>
                        <FooterTemplate>
                            <asp:Button style="font-family:Calibri" class="btn btn-dark form-control my-2 btn-sm" Text="Add" runat="server" CommandName="AddNew" ToolTip="AddNew" Height="30px" />
                        </FooterTemplate>
                    </asp:TemplateField>
                </Columns>
            </asp:GridView>
            <br />
            <asp:Label ID="lblSuccessMessage" Text="" runat="server" ForeColor="Green" />
            <br />
            <asp:Label ID="lblErrorMessage" Text="" runat="server" ForeColor="Red" />
                    </div>
                </div>
            </div>
        </div>
    </div>

</asp:Content>

<asp:Content ID="Content3" ContentPlaceHolderID="EvaluationContent" runat="server" EnableViewState="true">
</asp:Content>